### ISSUE TITLE
Need to include yum gpg key install

### ISSUE THREAD

**Issue by oniled** [MicrosoftDocs/windows-itpro-docs#8890]
install was still failing using yum until i added the following two Ansible tasks to install_mdatp.yml

    - get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/pki/rpm-gpg/microsoft.asc
        mode: '0644'
    - shell: rpm --import /etc/pki/rpm-gpg/microsoft.asc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 623e0469-826c-5cdf-6dc4-67c80e232d0f
* Version Independent ID: 0f6c33bc-711a-84d6-01bb-04d13f5a85a2
* Content: [Deploy Microsoft Defender ATP for Linux with Ansible - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@konstruktoid : Would this be the correct section, as copied from the docs page?

***

- Create the Ansible install and uninstall YAML files.

    - For apt-based distributions use the following YAML file:

        ```bash
        cat install_mdatp.yml
        ```
        ```Output
        - hosts: servers
            tasks:
                - include: ../roles/onboarding_setup.yml
                - include: ../roles/add_apt_repo.yml
                - apt:
                    name: mdatp
                    state: latest
                    update_cache: yes
        ```

***

```
- get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/pki/rpm-gpg/microsoft.asc
    mode: '0644'
- shell: rpm --import /etc/pki/rpm-gpg/microsoft.asc
```

**Comment by illfated** [comment]
Happy new year to all, by the way. 🙂

**Comment by konstruktoid** [comment]
Happy new year too you as well @illfated, and too you @oniled as well of course :)

You are correct about the key portion is missing, I'll fix a PR.
I would however use:
```yaml
- name: Add Microsoft DNF/YUM key
    rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
    when: ansible_os_family == "RedHat"
```
