### ISSUE TITLE
Several of the yamls are formatted incorrectly

### ISSUE THREAD

**Issue by natedogith1** [MicrosoftDocs/windows-itpro-docs#9348]
The uninstall files have task unindented, and the yum one has state indented too far.
```yaml
- hosts: servers
tasks:
    - yum:
       name: mdatp
        state: absent
```
The yum install file doesn't indent the yum parameters
```yaml
- hosts: servers
  tasks:
    - include: ../roles/onboarding_setup.yml
    - include: ../roles/add_yum_repo.yml
    - yum:
      name: mdatp
      state: latest
      enablerepo: packages-microsoft-com-prod-[channel]
```
There might have been other yaml issues as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 623e0469-826c-5cdf-6dc4-67c80e232d0f
* Version Independent ID: 0f6c33bc-711a-84d6-01bb-04d13f5a85a2
* Content: [Deploy Microsoft Defender ATP for Linux with Ansible - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**
